---
- name: AWS PLAYBOOK TEARDOWN 101
  connection: local
  hosts: aws_ec2
  gather_facts: false
  # The paramater region will be set for all ec2 modules by specifying it here under module_defaults
  module_defaults:
    group/aws:
      region: us-west-2
  tasks:
    - name: grab facts for workshop
      ec2_instance_facts:
        filters:
          instance-state-name: running
          "tag:Name": "TEST_INSTANCE"
      register: all_workshop_nodes

    - name: debug test
      debug:
        var: all_workshop_nodes

    # - name: debug aws ec2
    #   debug:
    #     var: hostvars['ec2-52-89-148-206.us-west-2.compute.amazonaws.com']
