---
- name: TOWER SETUP FOR AWS DEMO
  hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "url"
      prompt: "Tower URL?"
      default: "https://localhost"
    - name: "username"
      prompt: "Tower Username?"
      default: "admin"
    - name: "password"
      prompt: "Tower password?"
      default: "ansible"
    - name: "aws_access_key_id"
      prompt: "What is your aws_access_key_id?"
      default: "ABCDEFG"
    - name: "aws_secret_access_key"
      prompt: "What is your aws_secret_access_key?"
      default: "ABCDEFG/HIJKLMNOP"
  tasks:
    - name: ADD REPO AS PROJECT INTO TOWER
      tower_project:
        name: "AWS Project"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/IPvSean/aws_demo"
        tower_username: "{{username}}"
        tower_password: "{{password}}"
        tower_host: "{{url}}"

    - name: CREATE INVENTORY
      tower_inventory:
        name: "AWS DEMO INVENTORY"
        organization: Default
        tower_username: "{{username}}"
        tower_password: "{{password}}"
        tower_host: "{{url}}"

    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        name: AWS DEMO CREDENTIAL
        kind: aws
        username: "{{aws_access_key_id}}"
        password: "{{aws_secret_access_key}}"
        organization: Default
        tower_username: "{{username}}"
        tower_password: "{{password}}"
        tower_host: "{{url}}"

    - name: ADD AWS INVENTORY SOURCE
      tower_inventory_source:
        name: AWS Oregon
        inventory: "AWS DEMO INVENTORY"
        credential: "AWS DEMO CREDENTIAL"
        source: ec2
        update_on_launch: true
        overwrite: true
        source_regions: us-west-2
        tower_username: "{{username}}"
        tower_password: "{{password}}"
        tower_host: "{{url}}"

    - name: CREATE PROVISION RESOURCES JOB
      tower_job_template:
        name: "PROVISION AWS RESOURCES"
        job_type: "run"
        inventory: "AWS DEMO INVENTORY"
        project: "AWS Project"
        playbook: "provision_resources.yml"
        credential: "AWS DEMO CREDENTIAL"
        tower_username: "{{username}}"
        tower_password: "{{password}}"
        tower_host: "{{url}}"
    #
    #
    #
    # - tower_workflow_template:
    #     name: Workflow Template
    #     description: My very first Worflow Template
    #     organization: My optional Organization
    #     schema: "{{ lookup(file, my_workflow.json }}"
