- name: use wait for connection
  hosts: aws_ec2
  remote_user: ec2-user
  gather_facts: false

  tasks:
# This task will wait to get a ssh connetion to the
    - name: wait to connect
      wait_for:
        host: "{{ ansible_host }}"
        timeout: 800
        port: 22
      connection: local
